apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-rollout
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/pittar-demos/ContosoUniversity.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: s2i-dotnet
      params:
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/cicd/contoso:latest'
        - name: SKIP_PUSH
          value: 'false'
        - name: ENV_VARS
          value:
            - DOTNET_STARTUP_PROJECT=ContosoUniversity/ContosoUniversity.csproj
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-dotnet-chains
      workspaces:
        - name: source
          workspace: workspace
    - name: acs-image-scan
      params:
        - name: image
          value: 'image-registry.openshift-image-registry.svc:5000/cicd/contoso:latest'
        - name: output_format
          value: json
      runAfter:
        - s2i-dotnet
      taskRef:
        kind: ClusterTask
        name: acs-image-scan
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: acs-image-check
      params:
        - name: image
          value: 'image-registry.openshift-image-registry.svc:5000/cicd/contoso:latest'
      runAfter:
        - acs-image-scan
      taskRef:
        kind: ClusterTask
        name: acs-image-check
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: skopeo-tag-dev
      params:
        - name: srcImageURL
          value: >-
            docker://image-registry.openshift-image-registry.svc:5000/cicd/contoso@$(tasks.s2i-dotnet.results.IMAGE_DIGEST)
        - name: destImageURL
          value: 'docker://quay.io/pittar/contoso:dev'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - acs-image-check
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: workspace
    - name: rollout-dev
      params:
        - name: SCRIPT
          value: oc rollout restart deploy contoso -n contoso-dev
        - name: VERSION
          value: latest
      runAfter:
        - skopeo-tag-dev
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
    - name: skopeo-tag-test
      params:
        - name: srcImageURL
          value: >-
            docker://image-registry.openshift-image-registry.svc:5000/cicd/contoso@$(tasks.s2i-dotnet.results.IMAGE_DIGEST)
        - name: destImageURL
          value: 'docker://quay.io/pittar/contoso:test'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - rollout-dev
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: workspace
    - name: rollout-test
      params:
        - name: SCRIPT
          value: oc rollout restart deploy contoso -n contoso-test
        - name: VERSION
          value: latest
      runAfter:
        - skopeo-tag-test
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
  workspaces:
    - name: workspace
    - name: acs-central
