apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqlserver
    app.kubernetes.io/component: contoso-db
    app.kubernetes.io/instance: sqlserver
    app.kubernetes.io/part-of: contoso-app
    app.openshift.io/runtime: mssql
  name: sqlserver
  namespace: sqlserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sqlserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sqlserver
        deploymentconfig: sqlserver
    spec:
      containers:
        - env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: r3dh4t1!
          image: mcr.microsoft.com/mssql/rhel/server:2019-latest
          imagePullPolicy: Always
          name: sqlserver
          ports:
          - containerPort: 1433
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
