apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Contoso TEST
    openshift.io/display-name: Contoso TEST
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: contoso-test