apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cicd-namespace
  annotations:
    policy.open-cluster-management.io/standards: DevOps
    policy.open-cluster-management.io/categories: CI/CD Tools
    policy.open-cluster-management.io/controls: Namespace Config
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cicd-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  annotations:
                    openshift.io/description: Contoso CI/CD
                    openshift.io/display-name: Contoso CI/CD
                  labels:
                    argocd.argoproj.io/managed-by: developer-gitops
                  name: cicd
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cicd-roxctl-secret
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: roxsecrets
                  namespace: cicd
                type: Opaque
                data:
                  rox_api_token: |
                    {{ fromSecret "stackrox" "roxsecrets" "rox_api_token" }}
                  rox_central_endpoint: |
                    {{ fromSecret "stackrox" "roxsecrets" "rox_central_endpoint" }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: contoso-cicd-gitops
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Application
                apiVersion: argoproj.io/v1alpha1
                metadata:
                  annotations:
                    argocd.argoproj.io/sync-wave: "1"
                  labels:
                    gitops.ownedBy: developer-gitops
                  name: contoso-dev
                  namespace: developer-gitops
                spec:
                  destination:
                    namespace: contoso-dev
                    server: https://kubernetes.default.svc
                  project: default
                  source:
                    path: gitops/contoso-cicd
                    repoURL: https://github.com/pittar-demos/dotnet-devsecops.git
                    targetRevision: main
                  syncPolicy:
                    automated:
                      prune: false
                      selfHeal: true
                    syncOptions:
                      - ApplyOutOfSyncOnly=true
                    retry:
                      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
                      backoff:
                        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
                        factor: 2 # a factor to multiply the base duration after each failed retry
                        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-cicd-namespace
placementRef:
  name: placement-cicd-namespace
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: cicd-namespace
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-cicd-namespace
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: devsecops
        operator: In
        values:
          - "true"

