apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: contoso-dev-gitops
  annotations:
    policy.open-cluster-management.io/standards: Configuration
    policy.open-cluster-management.io/categories: Applications
    policy.open-cluster-management.io/controls: GitOps Config
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: contoso-dev-gitops
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Application
                apiVersion: argoproj.io/v1alpha1
                metadata:
                  annotations:
                    argocd.argoproj.io/sync-wave: "1"
                  labels:
                    gitops.ownedBy: developer-gitops
                  name: contoso-dev
                  namespace: developer-gitops
                spec:
                  destination:
                    namespace: contoso-dev
                    server: https://kubernetes.default.svc
                  project: default
                  source:
                    path: gitops/contoso-dev
                    repoURL: https://github.com/pittar-demos/dotnet-devsecops.git
                    targetRevision: main
                  syncPolicy:
                    automated:
                      prune: false
                      selfHeal: true
                    syncOptions:
                      - ApplyOutOfSyncOnly=true
                    retry:
                      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
                      backoff:
                        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
                        factor: 2 # a factor to multiply the base duration after each failed retry
                        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-contoso-dev-gitops
placementRef:
  name: placement-contoso-dev-gitops
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: contoso-dev-gitops
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-contoso-dev-gitops
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: devsecops
        operator: In
        values:
          - "true"

