namespace: contoso-dev

bases:
  - ../base/rbac/contoso-cicd-pipelines
  - ../base/app
  - ../base/database

resources:
  - namespace.yaml

images:
  - name: contoso
    newName: quay.io/pittar/contoso
    newTag: dev