apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Contoso DEV
    openshift.io/display-name: Contoso DEV
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: contoso-dev